BEGIN;

-- Ensure unique constraint exists
CREATE UNIQUE INDEX IF NOT EXISTS languages_label_key
ON languages (label);

INSERT INTO languages (label, flag) VALUES
('Afrikaans','🇿🇦'),
('Albanian','🇦🇱'),
('Amharic','🇪🇹'),
('Arabic','🇸🇦'),
('Armenian','🇦🇲'),
('Azerbaijani','🇦🇿'),
('Basque','🇪🇸'),
('Belarusian','🇧🇾'),
('Bengali','🇧🇩'),
('Bulgarian','🇧🇬'),
('Burmese','🇲🇲'),
('Catalan','🇪🇸'),
('Chinese','🇨🇳'),
('Croatian','🇭🇷'),
('Czech','🇨🇿'),
('Danish','🇩🇰'),
('Dutch','🇳🇱'),
('English','🇦🇺'),
('Estonian','🇪🇪'),
('Filipino','🇵🇭'),
('Finnish','🇫🇮'),
('French','🇫🇷'),
('Galician','🇪🇸'),
('Georgian','🇬🇪'),
('German','🇩🇪'),
('Greek','🇬🇷'),
('Gujarati','🇮🇳'),
('Hebrew','🇮🇱'),
('Hindi','🇮🇳'),
('Hungarian','🇭🇺'),
('Icelandic','🇮🇸'),
('Indonesian','🇮🇩'),
('Italian','🇮🇹'),
('Japanese','🇯🇵'),
('Javanese','🇮🇩'),
('Kannada','🇮🇳'),
('Kazakh','🇰🇿'),
('Khmer','🇰🇭'),
('Korean','🇰🇷'),
('Kyrgyz','🇰🇬'),
('Lao','🇱🇦'),
('Latvian','🇱🇻'),
('Lithuanian','🇱🇹'),
('Macedonian','🇲🇰'),
('Malay','🇲🇾'),
('Malayalam','🇮🇳'),
('Marathi','🇮🇳'),
('Mongolian','🇲🇳'),
('Nepali','🇳🇵'),
('Norwegian','🇳🇴'),
('Persian','🇮🇷'),
('Polish','🇵🇱'),
('Portuguese','🇵🇹'),
('Punjabi','🇮🇳'),
('Romanian','🇷🇴'),
('Romansh','🇨🇭'),
('Russian','🇷🇺'),
('Serbian','🇷🇸'),
('Sinhala','🇱🇰'),
('Slovak','🇸🇰'),
('Slovenian','🇸🇮'),
('Spanish','🇪🇸'),
('Swahili','🇹🇿'),
('Swedish','🇸🇪'),
('Tamil','🇮🇳'),
('Telugu','🇮🇳'),
('Thai','🇹🇭'),
('Turkish','🇹🇷'),
('Ukrainian','🇺🇦'),
('Urdu','🇵🇰'),
('Vietnamese','🇻🇳'),
('Zulu','🇿🇦'),
('Māori', '🇳🇿'),
('Fijian', '🇫🇯'),
('Yoruba', '🇳🇬'),
('Yiddish', '🌍'),
('Irish', '🇮🇪'),
('Welsh', '🏴'),
('Scottish Gaelic', '🏴'),
('Breton', '🇫🇷'),
('Dzongkha', '🇧🇹'),
('Uzbek', '🇺🇿'),
('Akan', '🇬🇭'),
('Shona', '🇿🇼'),
('Bemba', '🇿🇲'),
('Igbo', '🇳🇬'),
('Hausa', '🇳🇬'),
('Somali', '🇸🇴'),
('Latin', '🌍'),
('Maltese', '🇲🇹'),
('Aragonese', '🇪🇸'),
('Asturian', '🇪🇸'),
('Frisian', '🇳🇱'),
('Corsican', '🇫🇷'),
('Galician', '🇪🇸'),
('Occitan', '🇫🇷'),
('Sardinian', '🇮🇹'),
('Kurdish', '🌍'),
('Haitian Creole', '🇭🇹'),
('Guarani', '🇵🇾'),
('Quechua', '🌍'),
('Hawaiian', '🌍'),
('Samoan', '🇼🇸')
ON CONFLICT (label)
DO UPDATE SET flag = EXCLUDED.flag;

COMMIT;
