-- The languages found in the last part of the review tail — every remaining
-- token that turned out to be a real language with no reference row. Continues
-- 040, and ends the review.
--
-- Most of these carry only a name or two today, and are added anyway. A row is
-- cheap, it gives the next source somewhere to land, and a thin language still
-- has a use: a filter needs enough names to be worth offering, but a name's own
-- details can show its languages whatever their size.
--
-- Seven rows each stand in for several forms written separately in the sources,
-- following the rule that historical and regional forms fold into their
-- language: Sorbian (Upper and Lower), Sami (Northern Sami, Sámi), Nahuatl
-- (Classical), Tupi (Old Tupi), Leonese (Old Leonese), Phoenician (Punic) and
-- Gothic (Visigothic).
--
-- Egyptian is labelled Ancient Egyptian. Its names are Imhotep, Isis and
-- Nefertiti, and plain "Egyptian" reads as the modern country's Arabic.
--
-- Dothraki, High Valyrian and Sindarin are invented languages from fiction, each
-- with one name — Khaleesi, Daenerys, Galadriel. The tag is true of those names.
--
-- Every flag is the 🌍 placeholder, matching 037 to 040. ON CONFLICT DO NOTHING
-- so a later pass that sets proper flags is not undone by re-running this file.

BEGIN;

INSERT INTO languages (label, flag) VALUES
('''Are''are','🌍'),
('Afar','🌍'),
('Ancient Egyptian','🌍'),
('Aromanian','🌍'),
('Assamese','🌍'),
('Balinese','🌍'),
('Bashkir','🌍'),
('Betawi','🌍'),
('Bosnian','🌍'),
('Buginese','🌍'),
('Cape Verdean Creole','🌍'),
('Carolinian','🌍'),
('Central Bikol','🌍'),
('Chagatai','🌍'),
('Chavacano','🌍'),
('Chechen','🌍'),
('Chinook','🌍'),
('Chuvash','🌍'),
('Coptic','🌍'),
('Corsican','🌍'),
('Dagbanli','🌍'),
('Dakota','🌍'),
('Dalmatian','🌍'),
('Dothraki','🌍'),
('Edo','🌍'),
('Emilian','🌍'),
('Erzya','🌍'),
('Etruscan','🌍'),
('Ewe','🌍'),
('Extremaduran','🌍'),
('Farefare','🌍'),
('Fingallian','🌍'),
('Franco-Provençal','🌍'),
('Frankish','🌍'),
('Gallaecian','🌍'),
('Gallo','🌍'),
('Gothic','🌍'),
('Guanche','🌍'),
('Hanunoo','🌍'),
('High Valyrian','🌍'),
('Hiligaynon','🌍'),
('Hindustani','🌍'),
('Ibibio','🌍'),
('Idoma','🌍'),
('Ilocano','🌍'),
('Istriot','🌍'),
('Jamaican Patois','🌍'),
('Jamamadí','🌍'),
('Kalenjin','🌍'),
('Kanakanabu','🌍'),
('Karelian','🌍'),
('Kavalan','🌍'),
('Kaxuyana','🌍'),
('Kikuyu','🌍'),
('Kui (Indonesia)','🌍'),
('Ladino','🌍'),
('Lakota','🌍'),
('Latgalian','🌍'),
('Leonese','🌍'),
('Limburgish','🌍'),
('Lingala','🌍'),
('Lombard','🌍'),
('Louisiana Creole','🌍'),
('Luo','🌍'),
('Luxembourgish','🌍'),
('Maguindanao','🌍'),
('Maithili','🌍'),
('Malagasy','🌍'),
('Maltese','🌍'),
('Mam','🌍'),
('Manado','🌍'),
('Mapudungun','🌍'),
('Maranao','🌍'),
('Mirandese','🌍'),
('Murui Huitoto','🌍'),
('Nahuatl','🌍'),
('Nauruan','🌍'),
('Navajo','🌍'),
('Neapolitan','🌍'),
('Nheengatu','🌍'),
('Nobiin','🌍'),
('Old Median','🌍'),
('Old Turkic','🌍'),
('Oromo','🌍'),
('Pashto','🌍'),
('Phoenician','🌍'),
('Picard','🌍'),
('Puyuma','🌍'),
('Rapa Nui','🌍'),
('Romani','🌍'),
('Rukai','🌍'),
('Saaroa','🌍'),
('Saisiyat','🌍'),
('Sami','🌍'),
('Sandawe','🌍'),
('Saraiki','🌍'),
('Sardinian','🌍'),
('Seychellois Creole','🌍'),
('Shelta','🌍'),
('Sherbro','🌍'),
('Silesian','🌍'),
('Sindarin','🌍'),
('Sindhi','🌍'),
('Soninke','🌍'),
('Sorbian','🌍'),
('Sranan Tongo','🌍'),
('Swazi','🌍'),
('Tahitian','🌍'),
('Tajik','🌍'),
('Tatar','🌍'),
('Thao','🌍'),
('Thracian','🌍'),
('Tibetan','🌍'),
('Tocharian B','🌍'),
('Tokelauan','🌍'),
('Tongan','🌍'),
('Trinidadian Creole','🌍'),
('Tupi','🌍'),
('Turkmen','🌍'),
('Tuvaluan','🌍'),
('Ulwa (New Guinea)','🌍'),
('Unami','🌍'),
('Urhobo','🌍'),
('Vandalic','🌍'),
('Venetian','🌍'),
('Veps','🌍'),
('Vilamovian','🌍'),
('West Circassian','🌍'),
('Yakut','🌍'),
('Zazaki','🌍')
ON CONFLICT (label) DO NOTHING;

COMMIT;
